#!/usr/bin/env bash

#
# Copyright (c) 2021.  Jefferson Science Associates, LLC.
# Subject to the terms in the LICENSE file found in the top-level directory.
# Author gyurjyan
#

BASEDIR=$(cd "$(dirname "${BASH_SOURCE[0]}")"/.. && pwd)

if [ -z "${ERSAP_HOME}" ]; then
    ERSAP_HOME=${BASEDIR}
    export ERSAP_HOME
fi

# find plugins directory
if [ -n "${ERSAP_PLUGINS}" ]; then
    if [ ! -d "${ERSAP_PLUGINS}" ]; then
        echo "Error: \$ERSAP_PLUGINS is not a directory."
        exit 1
    fi
    plugins_dir="${ERSAP_PLUGINS}"
else
    plugins_dir="${ERSAP_HOME}/plugins"
fi

# set default classpath
if [ -z "${CLASSPATH}" ]; then
    CLASSPATH="${ERSAP_HOME}/lib/*"

    # Add every plugin
    for plugin in "${plugins_dir}"/*/; do
        plugin=${plugin%*/}
        if [ "${plugin##*/}" = "clas12" ]; then # COAT has special needs
            CLASSPATH+=":${plugin}/lib/clas/*:${plugin}/lib/services/*"
        elif [ "${plugin##*/}" = "grapes" ]; then # Grapes also has special needs
            CLASSPATH+=":${plugin}/lib/core/*:${plugin}/lib/services/*"
        else
            CLASSPATH+=":${plugin}/services/*:${plugin}/lib/*"
        fi
    done

    CLASSPATH+=":${ERSAP_HOME}/services/*"
    export CLASSPATH
fi

# set java.library.path
java_lib_path=
for plugin in "${plugins_dir}"/*/; do
    plugin=${plugin%*/}
    if [ "${plugin##*/}" = "clas12" ]; then # COAT has special needs
        java_lib_path+=":${plugin}/lib/clas"
    elif [ "${plugin##*/}" = "grapes" ]; then # Grapes also has special needs
        java_lib_path+=":${plugin}/lib/core"
    else
        java_lib_path+=":${plugin}/lib"
    fi
done

if [ -n "${JAVA_OPTS}" ]; then
    jvm_options=(${JAVA_OPTS})
else
    jvm_options=(-Xms1024m -XX:+UseNUMA -XX:+UseBiasedLocking)
#jvm_options=(-Xms3g -Xmx3g -XX:NewRatio=3 -XX:MaxNewSize=1g -XX:SurvivorRatio=6 -XX:+UseNUMA -XX:+TieredCompilation -XX:+UseBiasedLocking -XX:+AggressiveOpts)
fi

java_wrapper=${ERSAP_HOME}/lib/ersap/run-java

exec "${java_wrapper}" "${jvm_options[@]}" -Djava.library.path="${java_lib_path}" org.jlab.epsci.ersap.sys.Dpe "$@"
