#!/bin/bash

#
# Copyright (c) 2021.  Jefferson Science Associates, LLC.
# Subject to the terms in the LICENSE file found in the top-level directory.
# Author gyurjyan
#

DEV_TAG=ersapdk-$CACHE_TAG
DEV_TAG=${DEV_TAG%-latest}

docker push $DOCKER_REPO:$DEV_TAG
