#!/bin/sh

#
# Copyright (c) 2021.  Jefferson Science Associates, LLC.
# Subject to the terms in the LICENSE file found in the top-level directory.
# Author gyurjyan
#

exec ./scripts/exec-class org.jlab.epsci.ersap.std.orchestrators.GenericOrchestrator "$@"
